name: flutter_term2_blarbla_car
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Eesti
      fonts:
        - asset: assets/fonts/GT-Eesti-Bold.otf
        - asset: assets/fonts/GT-Eesti-Light.otf
        - asset: assets/fonts/GT-Eesti-Regular.otf
        - asset: assets/fonts/GT-Eesti-Thin.otf
  assets:
    - assets/images/
